<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CheckpointSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>17b2e00d-636b-4d83-83e0-4e247c7e7c59</testSuiteGuid>
   <testCaseLink>
      <guid>1928d2dd-cf03-4f1b-aa5b-994afb6ad344</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckPoints/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a119eff3-92d2-4b34-ac93-1035e2ee1a94</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/MSSData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a119eff3-92d2-4b34-ac93-1035e2ee1a94</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>c0ebd3a4-3301-4ed0-8f5b-51936efd51fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a119eff3-92d2-4b34-ac93-1035e2ee1a94</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>b8aa92e1-467e-4e59-a01a-27228c0196ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a119eff3-92d2-4b34-ac93-1035e2ee1a94</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>9f6753de-a577-4e61-b3d9-304d85b2d5a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>15dae03f-ee3f-4818-9e65-4e2221b28f31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckPoints/Issue navigator</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8b1a7300-0d84-4dfa-b258-fbc19dd876eb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/MSSData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8b1a7300-0d84-4dfa-b258-fbc19dd876eb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Protocol</value>
         <variableId>a8bce4f8-a7e1-42b1-a131-28b2d8021d20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8b1a7300-0d84-4dfa-b258-fbc19dd876eb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>MSS</value>
         <variableId>1019f73b-716e-443a-b611-74af35345290</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7e3f1b2-76cf-465e-b166-e86ff32363ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CheckPoints/LogOut</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>31b61a4c-9911-43b5-8127-74f869156322</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/MSSData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>31b61a4c-9911-43b5-8127-74f869156322</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ForgotText</value>
         <variableId>de00dfce-369c-449e-b970-d5d0c3941fd2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
