<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>StageSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7c8c0369-3c00-49a3-9d49-663838cb18eb</testSuiteGuid>
   <testCaseLink>
      <guid>66605f9d-698f-46cf-9124-ea06430e5b6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IQVIA_MSS/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>26812a31-7ea2-4e9a-a0c9-d5be117da5ef</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/MSSSTage</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da95805f-f448-4817-b9a6-472dcb169f1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>26812a31-7ea2-4e9a-a0c9-d5be117da5ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>3d8ea049-0864-40a0-8484-b5cd0fc68908</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>26812a31-7ea2-4e9a-a0c9-d5be117da5ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>9ef0ad54-6ded-4bb6-b422-d8e97f1f34b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1d8d145-d3d4-4a8e-8d18-5a9ccef7ceb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IQVIA_MSS/LogOut</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d1d5ac3b-4b3d-416a-803e-f1462f27c646</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/MSSSTage</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d1d5ac3b-4b3d-416a-803e-f1462f27c646</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ForgotText</value>
         <variableId>21b9c449-2638-43c0-97d4-802e9876ab4f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
