<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IN</name>
   <tag></tag>
   <elementGuidId>0a53e0c5-106d-48dc-b807-ad320af7fbd1</elementGuidId>
   <imagePath>Screenshots/Targets/Select/IN.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Select/IN.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[text()='Issue Navigator'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e7390aea-e4ea-4e2c-b34c-9a505f5f75b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678261402532</value>
      <webElementGuid>92756cc5-cc91-4952-98df-83c6dc0d203f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
