<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_User DashboardNavigation</name>
   <tag></tag>
   <elementGuidId>99d63a49-f235-4447-a427-bd6d3bb16b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---btn.Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---inSiteHeaderLayout.Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---has_pulldown.appian-context-ux-mouse-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>684a1c9c-b19f-42c3-b822-e45259afa86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3439753f-1aca-4885-949a-c394b56a9102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---btn Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---inSiteHeaderLayout Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---has_pulldown appian-context-ux-mouse-focus</value>
      <webElementGuid>b1861a96-a85f-410f-84d7-5d887d576398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e81279b4-a22b-4b6d-8dc5-bec7fcdf419b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb4cfa5a-658a-4b4d-8ea7-1179443e459f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User DashboardNavigation</value>
      <webElementGuid>a1050c28-718c-4e98-9f51-683c59bcec7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4e5018144c0a476bb5ba3996bb7978c4_header_site_contextWidget&quot;)/div[@class=&quot;Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---btn_wrapper tether-target tether-out-of-bounds tether-out-of-bounds-left tether-element-attached-top tether-element-attached-right tether-target-attached-bottom tether-target-attached-right tether-enabled&quot;]/button[@class=&quot;Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---btn Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---inSiteHeaderLayout Button_SITE_HEADER_LAYOUT_NAME_NAVIGATION_MENU---has_pulldown appian-context-ux-mouse-focus&quot;]</value>
      <webElementGuid>ef1d7349-48d1-4ece-b6be-506c4a82b44b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>51a47613-4f51-4a63-962c-fbcc36d1015c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4e5018144c0a476bb5ba3996bb7978c4_header_site_contextWidget']/div/button</value>
      <webElementGuid>93ed2843-2aa3-4ef8-9f3b-4e4bbf4e3b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[1]/following::button[1]</value>
      <webElementGuid>793d8120-fb08-4a9e-b966-134d80fc4ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::button[1]</value>
      <webElementGuid>e266df40-6e0c-494f-82f0-ab7aef347df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Dashboard']/parent::*</value>
      <webElementGuid>2927808e-c520-48bd-b724-f6c62b5f3c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>87f70950-3c0d-4834-80a4-4afc4a94491f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'User DashboardNavigation' or . = 'User DashboardNavigation')]</value>
      <webElementGuid>b91e7ec2-d576-4fbf-bd3e-c975fff97645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
