<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserIcon</name>
   <tag></tag>
   <elementGuidId>e6183db3-e9cb-4190-8060-3293575ddf1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.elements---global_a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='4e5018144c0a476bb5ba3996bb7978c4_header_site_profile']/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>da4074b5-4d59-486b-87c9-34b7a0ea5aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4e5018144c0a476bb5ba3996bb7978c4_header_site_profile&quot;)/div[@class=&quot;UserProfileLayout---current_user_menu_wrapper&quot;]/a[@class=&quot;elements---global_a&quot;]/span[1]</value>
      <webElementGuid>e048173d-d488-445c-88fb-9c7828eaceb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4e5018144c0a476bb5ba3996bb7978c4_header_site_profile']/div/a/span</value>
      <webElementGuid>e706efbd-571a-48e7-886f-b6dd97754af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>6a740074-5592-4830-a7a1-c9e3bd3ebae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
