<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>6588d77a-a3aa-41d9-90b6-e01ae755762d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button---btn.Button---default_direction.Button---secondary.Button---small.appian-context-first-in-list.appian-context-last-in-list.Button---inSideBySide.Button---search.appian-context-ux-mouse-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9a8bc93-ebf2-4471-920c-340cb2271d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b31ff1d-e653-42d0-bbdb-bfcb5ab0a5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button---btn Button---default_direction Button---secondary Button---small appian-context-first-in-list appian-context-last-in-list Button---inSideBySide Button---search appian-context-ux-mouse-focus</value>
      <webElementGuid>b14880b9-4428-4edf-9671-e4c42c119cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>a3a58797-7bd2-498b-96cf-32679499b16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sitesBody&quot;)/div[1]/div[@class=&quot;ContentLayout---content_layout&quot;]/div[@class=&quot;FieldLayout---field_layout FieldLayout---margin_below_none FieldLayout---margin_above_none appian-context-last-in-list&quot;]/div[@class=&quot;FieldLayout---input_below&quot;]/div[@class=&quot;ContentLayout---content_layout ContentLayout---flush&quot;]/div[@class=&quot;ContentLayout---content_layout ContentLayout---flush&quot;]/div[@class=&quot;MultiColumnLayout---column_layout MultiColumnLayout---margin_above_none MultiColumnLayout---stack_when_phone&quot;]/div[@class=&quot;ColumnLayout---column ColumnLayout---column_padding_standard ColumnLayout---align_start ColumnLayout---middle ColumnLayout---width_auto ColumnLayout---stack_when_phone&quot;]/div[@class=&quot;SideBySideGroup---side_by_side SideBySideGroup---default_direction SideBySideGroup---middle&quot;]/div[@class=&quot;SideBySideItem---flex_item SideBySideItem---default_direction SideBySideItem---dense SideBySideItem---minimize appian-context-last-in-list&quot;]/div[@class=&quot;ButtonLayout2---button_layout ButtonLayout2---align_start ButtonLayout2---margin_below_none ButtonLayout2---margin_above_none&quot;]/div[@class=&quot;Button---btn_wrapper Button---default_direction appian-context-first-in-list appian-context-last-in-list Button---in_align_start Button---pointer_events&quot;]/button[@class=&quot;Button---btn Button---default_direction Button---secondary Button---small appian-context-first-in-list appian-context-last-in-list Button---inSideBySide Button---search appian-context-ux-mouse-focus&quot;]</value>
      <webElementGuid>f5926134-1ceb-4f0e-aab6-38603d20c9c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>47dc71ae-0566-4c4f-9720-36d2ba6c9bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sitesBody']/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>41bf76a4-e527-4917-a564-ce5d4609b760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search IN Customer Projects'])[1]/following::button[1]</value>
      <webElementGuid>b8e4aefb-8032-4369-bfed-5b2612f634c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::button[1]</value>
      <webElementGuid>5f74fc8a-e5ca-4bc7-b3a0-6092fb813fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>1d3d4664-a8db-4c85-8669-8b9a18294b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>fa8b46d3-07fa-42ff-8cf1-d014ee39eef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>0011e3e4-4c3c-4ecd-b41b-adefa8ea4142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
