<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputfor protocol</name>
   <tag></tag>
   <elementGuidId>cadb71a0-0d6d-4599-acaf-9b1970a6d8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3a6df69df02f06b57b2ce3840285a057</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Search IN Customer Projects']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaffe9de-6231-40df-8bb4-6f3d68cc0ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3a6df69df02f06b57b2ce3840285a057</value>
      <webElementGuid>2525871f-4689-4c55-8eef-919ae5971a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9491fd50-c2a4-4210-8f8f-04d9531d18db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput---text TextInput---align_start TextInput---inSideBySideItem appian-context-ux-mouse-focus</value>
      <webElementGuid>98c194ef-a40c-4a8b-a68f-ee01597a332b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search IN Customer Projects</value>
      <webElementGuid>591efb61-c060-4546-b80e-ff4af10d9577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3a6df69df02f06b57b2ce3840285a057&quot;)</value>
      <webElementGuid>be9b5c5b-4b5f-43b1-a781-ec57812b1389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8120a7c9-3837-43a1-850e-73c70f94bccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sitesBody']/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>7ec0146b-f417-4951-bd60-bd0b5e46ce26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dc43edf7-8157-479e-9229-e04fbff67b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3a6df69df02f06b57b2ce3840285a057' and @type = 'text' and @placeholder = 'Search IN Customer Projects']</value>
      <webElementGuid>6bc18e7c-82e5-4dc9-ac55-8210807bceb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
