<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link</name>
   <tag></tag>
   <elementGuidId>c3afd175-9cce-4ad6-96c6-a61a81da3769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.elements---global_a.appian-context-ux-mouse-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sitesBody']/div/div/div/div[2]/div/div[2]/div/table/tbody/tr/td/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>353c84fa-3078-4614-804e-c227ff3ab70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://quintilestest.appiancloud.com/suite/sites/dr-dashboard/page/projects/record/lMBQZ8EKEvHukMx5v1SVqItuq_expXGc_ATQdvOjfBRjuHm8zfOCkYrZtfrwJbOyBHx8ihcxdheVBj-M2mDi3E8yY8YT_AgTos3mziR_b3IiUfksQ/view/summary</value>
      <webElementGuid>120339fc-5e9c-464c-a174-4cbce5593ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0afb2f67-5774-4cc7-bc45-5687dea187b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elements---global_a appian-context-ux-mouse-focus</value>
      <webElementGuid>10a841bf-d8e1-4fa5-9ace-4a7f0d74cc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>H8O-US-BOO4</value>
      <webElementGuid>d0b4f715-18fb-4aad-b84e-1e3e49fe90ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sitesBody&quot;)/div[1]/div[@class=&quot;ContentLayout---content_layout&quot;]/div[@class=&quot;FieldLayout---field_layout FieldLayout---margin_below_none FieldLayout---margin_above_none appian-context-last-in-list&quot;]/div[@class=&quot;FieldLayout---input_below&quot;]/div[@class=&quot;ContentLayout---content_layout ContentLayout---flush&quot;]/div[2]/div[@class=&quot;PagingGridLayout---scrollable_content&quot;]/table[@class=&quot;PagingGridLayout---table PagingGridLayout---scrollable PagingGridLayout---striped&quot;]/tbody[1]/tr[1]/td[1]/div[1]/p[@class=&quot;LinkGroup---link_group LinkGroup---align_start elements---global_p&quot;]/a[@class=&quot;elements---global_a appian-context-ux-mouse-focus&quot;]</value>
      <webElementGuid>4c42d1e3-b3f3-4298-bbe3-37b8712a1146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sitesBody']/div/div/div/div[2]/div/div[2]/div/table/tbody/tr/td/div/p/a</value>
      <webElementGuid>1a3e55b2-284a-43cb-a1d0-7809dac8060e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'H8O-US-BOO4')]</value>
      <webElementGuid>9c53f20f-8a60-4392-aabf-5d55c441153d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='H8O-US-BOO4']/parent::*</value>
      <webElementGuid>5e1925e1-15a6-465f-b4f2-bda12d3c8d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://quintilestest.appiancloud.com/suite/sites/dr-dashboard/page/projects/record/lMBQZ8EKEvHukMx5v1SVqItuq_expXGc_ATQdvOjfBRjuHm8zfOCkYrZtfrwJbOyBHx8ihcxdheVBj-M2mDi3E8yY8YT_AgTos3mziR_b3IiUfksQ/view/summary')]</value>
      <webElementGuid>2ccd341c-f296-4ff2-a5df-f011eaf7cf89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>63dfcbc5-5bed-4337-b9b2-ed91064e535e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://quintilestest.appiancloud.com/suite/sites/dr-dashboard/page/projects/record/lMBQZ8EKEvHukMx5v1SVqItuq_expXGc_ATQdvOjfBRjuHm8zfOCkYrZtfrwJbOyBHx8ihcxdheVBj-M2mDi3E8yY8YT_AgTos3mziR_b3IiUfksQ/view/summary' and (text() = 'H8O-US-BOO4' or . = 'H8O-US-BOO4')]</value>
      <webElementGuid>028907a7-c238-4aa5-b7ef-ecbc103204ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
